// dialogue.js - Generated by Unified Content Editor
console.log('=== DIALOGUE.JS IS LOADING ===');

const dialogueDatabase = {
  "eddie_video_clerk": {
    "name": "Eddie",
    "sprite": "villager_worker",
    "isShopkeeper": false,
    "lines": [
      {
        "text": "Hey! Ready for another shift?",
        "requires": {},
        "sets": {}
      },
      {
        "text": "Someone returned that tape this morning. Never seen one like it. Weird symbols and all. Check if it's damaged, will ya?",
        "requires": {
          "flags": {
            "vhsAppeared": true,
            "eddieCommentedOnVHS": false
          }
        },
        "sets": {
          "eddieCommentedOnVHS": true
        }
      }
    ]
  }
};

function getDialogue(npcId, gameState) {
    const npc = dialogueDatabase[npcId];
    if (!npc) {
        console.error('NPC "' + npcId + '" not found');
        return { text: "...", sets: null };
    }
    
    if (!gameState.flags) gameState.flags = {};
    
    for (let i = npc.lines.length - 1; i >= 0; i--) {
        const line = npc.lines[i];
        if (meetsRequirements(line.requires, gameState)) {
            return processDialogue(line, gameState, npcId);
        }
    }
    
    return processDialogue(npc.lines[0], gameState, npcId);
}

function meetsRequirements(requires, gameState) {
    if (!requires) return true;
    
    if (requires.level !== undefined && gameState.player.level < requires.level) return false;
    if (requires.gold !== undefined && gameState.player.gold < requires.gold) return false;
    if (requires.hasItem && !gameState.player.inventory.includes(requires.hasItem)) return false;
    
    if (requires.flags) {
        for (const [flag, requiredValue] of Object.entries(requires.flags)) {
            const currentValue = gameState.flags?.[flag];
            if (typeof requiredValue === 'boolean') {
                if (Boolean(currentValue) !== requiredValue) return false;
            } else if (currentValue !== requiredValue) {
                return false;
            }
        }
    }
    
    return true;
}

function processDialogue(line, gameState, npcId) {
    if (line.sets) {
        if (!gameState.flags) gameState.flags = {};
        Object.assign(gameState.flags, line.sets);
    }
    
    return {
        text: line.text,
        sets: line.sets || null,
        npcName: dialogueDatabase[npcId]?.name || "Unknown"
    };
}

function getNPCData(npcId) {
    return dialogueDatabase[npcId] || null;
}

console.log('=== DIALOGUE.JS LOADED ===');
console.log('Loaded ' + Object.keys(dialogueDatabase).length + ' NPCs');