// events.js - Generated by Unified Content Editor
console.log('=== EVENTS.JS IS LOADING ===');

const eventHandlers = {
    'vhs_appears': {
        // Strange VHS tape appears at the video store on day 3
        canTrigger: (gs) => {
            if (gs.flags.vhs_appears_completed) return false;
            return gs.dayCounter >= 3 &&
                   !gs.flags.vhsAppeared &&
                   gs.currentMap === 'Video_Store';
        },
        
        onTrigger: (gs) => {
            console.log('EVENT: vhs_appears');
            
            const location = '8,5';
            if (!treasureContents['Video_Store']) treasureContents['Video_Store'] = {};
            treasureContents['Video_Store'][location] = { gold: 0, items: ['magic_vhs'] };
            const [x, y] = location.split(',').map(Number);
            const row = gs.world.tiles[y];
            gs.world.tiles[y] = row.substring(0, x) + '$' + row.substring(x + 1);
            renderWorld();
            addMessage("Something's different about the store today...", CGA.CYAN);
            gs.flags.vhs_appears_completed = true;
        }
    }
};

function checkEvents(gameState) {
    Object.entries(eventHandlers).forEach(([eventId, handler]) => {
        try {
            if (handler.canTrigger(gameState)) {
                console.log(`Triggering event: ${eventId}`);
                handler.onTrigger(gameState);
            }
        } catch (error) {
            console.error(`Error in event ${eventId}:`, error);
        }
    });
}

// ===== REST HOOK SYSTEM =====
const restHooks = {
    beforeRest: [],
    afterRest: []
};

function runBeforeRestHooks(gameState, location) {
    for (const hook of restHooks.beforeRest) {
        try {
            const shouldCancel = hook(gameState, location);
            if (shouldCancel) {
                console.log('Rest cancelled by hook');
                return true;
            }
        } catch (error) {
            console.error('Error in beforeRest hook:', error);
        }
    }
    return false;
}

function runAfterRestHooks(gameState, location) {
    restHooks.afterRest.forEach(hook => {
        try {
            hook(gameState, location);
        } catch (error) {
            console.error('Error in afterRest hook:', error);
        }
    });
}

console.log('=== EVENTS.JS LOADED ===');
console.log(`Registered ${Object.keys(eventHandlers).length} event handlers`);