// events.js - Generated by Story Editor
console.log('=== EVENTS.JS IS LOADING ===');

const eventHandlers = {
    'vhs_appears': {
        // Strange VHS tape appears at the video store on day 3
        canTrigger: (gs) => {
            if (gs.flags.vhsAppeared) return false;
            return gs.dayCounter >= 3 &&
                   gs.flags.vhsAppeared === false &&
                   gs.currentMap === 'Video_Store';
        },
        
        onTrigger: (gs) => {
            console.log('EVENT: vhs_appears');
            
            const location = '8,5';
            if (!treasureContents['Video_Store']) treasureContents['Video_Store'] = {};
            treasureContents['Video_Store'][location] = { gold: 0, items: ['magic_vhs'] };
            const [x, y] = location.split(',').map(Number);
            const row = gs.world.tiles[y];
            gs.world.tiles[y] = row.substring(0, x) + '$' + row.substring(x + 1);
            renderWorld();
            addMessage("Something's different about the store today...", CGA.CYAN);
            gs.flags.vhsAppeared = true;
        }
    },

    'vhs_pickup': {
        // Player picks up the mysterious VHS tape
        canTrigger: (gs) => {
            if (gs.flags.pickedUpVHS) return false;
            return gs.player.inventory.includes('magic_vhs') &&
                   gs.flags.pickedUpVHS === false;
        },
        
        onTrigger: (gs) => {
            console.log('EVENT: vhs_pickup');
            addMessage("The tape feels unnaturally cold in your hands.", CGA.MAGENTA);
            addMessage("You can't quite focus on the label...", CGA.MAGENTA);
            addMessage("Maybe you should watch it when you get home.", CGA.CYAN);
            addJournalEntry('The Unmarked Tape', [{ type: 'text', content: 'Found a strange VHS at work today. The label is covered in symbols I don\'t recognize. Eddie said someone returned it this morning. Who rents tapes like this? I should probably watch it when I get home. Make sure it\'s not damaged.' }]);
            gs.flags.pickedUpVHS = true;
        }
    },

    'vhs_transport': {
        // Watching the VHS at home triggers the transport to the goblin realm
        canTrigger: (gs) => {
            if (gs.flags.transported) return false;
            return gs.player.x === 6 && gs.player.y === 1 && gs.currentMap === 'Overworld' &&
                   gs.player.inventory.includes('magic_vhs') &&
                   gs.flags.transported === false &&
                   gs.flags.tryingToRestWithVHS === true;
        },
        
        onTrigger: (gs) => {
            console.log('EVENT: vhs_transport');
            fadeToBlack(() => {
    addMessage("===================");
    addMessage("You can't stop thinking about that tape...");
    addMessage("You put it in the VCR.");
    addMessage("===================");
    
    setTimeout(() => {
        addMessage("Static fills the screen.", CGA.CYAN);
        
        setTimeout(() => {
            addMessage("The static forms patterns...", CGA.MAGENTA);
            
            setTimeout(() => {
                addMessage("The patterns become symbols...", CGA.MAGENTA);
                
                setTimeout(() => {
                    addMessage("The symbols burn into your eyes...", CGA.MAGENTA);
                    
                    setTimeout(() => {
                        addMessage("===================");
                        addMessage("Everything goes white.");
                        addMessage("===================");
                        
                        setTimeout(() => {
                            // TRANSPORT TO GOBLIN REALM
                            loadMap('Dungeon1');
                            gs.player.x = 10;
                            gs.player.y = 7;
                            
                            // Remove VHS from inventory
                            const vhsIndex = gs.player.inventory.indexOf('magic_vhs');
                            if (vhsIndex > -1) {
                                gs.player.inventory.splice(vhsIndex, 1);
                            }
                            
                            gs.flags.inMansfield = false;
                            gs.flags.inGoblinRealm = true;
                            
                            setTimeout(() => {
                                clearFade();
                                addMessage("===================");
                                addMessage("You wake up on cold stone.");
                                addMessage("This isn't your bedroom.");
                                addMessage("This isn't Mansfield.");
                                addMessage("===================");
                                
                                addJournalEntry('What Just Happened?', [
                                    { type: 'text', content: "I watched the tape. I shouldn't have watched the tape." },
                                    { type: 'text', content: 'Now I\'m... somewhere else. Stone walls. Cold air. The smell of damp earth.' },
                                    { type: 'text', content: 'Where am I? How do I get home?' }
                                ]);
                                
                                renderWorld();
                                updateExploration();
                                updateStatus();
                            }, 500);
                        }, 2000);
                    }, 1500);
                }, 1500);
            }, 1500);
        }, 1500);
    }, 1000);
});
            gs.flags.transported = true;
        }
    }
};

function checkEvents(gameState) {
    Object.entries(eventHandlers).forEach(([eventId, handler]) => {
        try {
            if (handler.canTrigger(gameState)) {
                console.log(`Triggering event: ${eventId}`);
                handler.onTrigger(gameState);
            }
        } catch (error) {
            console.error(`Error in event ${eventId}:`, error);
        }
    });
}

// ===== REST HOOK SYSTEM =====
const restHooks = {
    beforeRest: [
        // VHS watching hook
        function checkVHSWatching(gameState, location) {
            const currentTile = gameState.world.tiles[gameState.player.y]?.[gameState.player.x];
            
            if (currentTile === 'B' && gameState.player.inventory.includes('magic_vhs')) {
                gameState.flags.tryingToRestWithVHS = true;
                checkEvents(gameState);
                
                if (gameState.flags.transported) {
                    gameState.flags.tryingToRestWithVHS = false;
                    return true; // Cancel rest
                }
                
                gameState.flags.tryingToRestWithVHS = false;
            }
            
            return false;
        }
    ],
    
    afterRest: [
        // Day counter advancement
        function advanceDay(gameState, location) {
            if (location === 'bed') {
                gameState.dayCounter = (gameState.dayCounter || 0) + 1;
                console.log(`Day advanced to: ${gameState.dayCounter}`);
                
                // Reset daily flags
                gameState.dailyFlags = {
                    talkedToEddie: false,
                    visitedCoffeeShop: false,
                    wentToBar: false
                };
                
                // Show day number
                addMessage(`Day ${gameState.dayCounter}`, CGA.CYAN);
                
                // Check for events that trigger on new day
                checkEvents(gameState);
            }
        }
    ]
};

function runBeforeRestHooks(gameState, location) {
    for (const hook of restHooks.beforeRest) {
        try {
            const shouldCancel = hook(gameState, location);
            if (shouldCancel) {
                console.log('Rest cancelled by hook');
                return true;
            }
        } catch (error) {
            console.error('Error in beforeRest hook:', error);
        }
    }
    return false;
}

function runAfterRestHooks(gameState, location) {
    restHooks.afterRest.forEach(hook => {
        try {
            hook(gameState, location);
        } catch (error) {
            console.error('Error in afterRest hook:', error);
        }
    });
}

console.log('=== EVENTS.JS LOADED ===');
console.log(`Registered ${Object.keys(eventHandlers).length} event handlers`);
console.log(`Registered ${restHooks.beforeRest.length} beforeRest hooks`);
console.log(`Registered ${restHooks.afterRest.length} afterRest hooks`);